### ISSUE TITLE
Layout for badge/pass

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#74]
# Example

![scar-1](https://cloud.githubusercontent.com/assets/1506457/12866231/a16ade94-ccae-11e5-87d1-4072a27c7ef9.jpg)

![scar-2](https://cloud.githubusercontent.com/assets/1506457/12866239/c28c6570-ccae-11e5-8759-7ec0a9dd120f.jpg)
# TODO
- [ ] Create layout. **The layout could include the Scavenger Hunt, #37.**
- [ ] Get cost for print the badges.
- [ ] Get cost for vinyl pouches/badge holder. E.g [Type EV1 (vertical)](http://www.databac.com/accessories/vinyl_pouches/): large-format event pass holder with overall size: 128 x 180mm that Accepts inserts size 118 x 160mm.
- [ ] Get cost for lanyards/necklaces.

**Comment by rgaiacs** [comment]
@taliaga Could you check the cost for this? The paper should be something close to [card stock](https://en.wikipedia.org/wiki/Card_stock).

**Comment by taliaga** [comment]
OMW!

**Comment by rgaiacs** [comment]
@taliaga Você pode me ligar nessa sexta?

**Comment by rgaiacs** [comment]
@taliaga você consegue cotar o preço de  "vinyl pouches/badge holder" e "cost for lanyards/necklaces"? Se for mais barato posso comprar isso nos Estados Unidos ou Reino Unido, levar na mala e **para pegar o reembolso depois**.

**Comment by taliaga** [comment]
Posso, vou ver o que acho de preco por aqui. Porem acredito que será mais barato trazer de fora :)

**Comment by rgaiacs** [comment]
@xmnlab Se formos comprar fora é possível que a FAPEU faça o pagamento e mande entregar no meu endereço?

**Comment by xmnlab** [comment]
Espero que sim, vou verificar isso.

**Comment by rgaiacs** [comment]
![badge](https://cloud.githubusercontent.com/assets/1506457/14077203/30859ede-f4e1-11e5-94ff-1daa841b77e5.png)

**Comment by rgaiacs** [comment]
# Exemplo

![badge2](https://cloud.githubusercontent.com/assets/1506457/14393199/789e8412-fdbd-11e5-9f27-950659f67cc5.png)

# Informações presentes
1. Nickname ou como você deseja ser chamado.
2. Nome completo
3. Afiliação (empresa, universidade, associação)
4. 3 usernames ou domínios
   
   Se você usa o mesmo username para mais de um serviço você pode indicá-los. Por exemplo, utilizo `rgaiacs` para GitHub, GitLab, Twitter e Facebook, e `r.gaia.cs` para Google+ e Skype. Então posso ter ambos usernames ao lado do icone desses serviços mais o meu domínio, `rgaiacs.com`.

# TODO
1. Aprovação.
2. Cotação.
3. Coleta de informação.
4. Automatização. Podemos usar Jinja2. :-)

**Comment by xmnlab** [comment]
+1

**Comment by taliaga** [comment]
See comment on #95

**Comment by rgaiacs** [comment]
Parcialmente realizado.
