### ISSUE TITLE
Screenshare videos

### ISSUE THREAD

**Issue by rgaiacs** [scipy-latinamerica/scipyla2016#75]
O @alexandrejaguar sugeriu publicar semanalmente um vídeo sobre algum assunto para divulgar o evento. Os vídeos podem ser em português, espanhol, inglês ou qualquer outra língua (alguém que saiba tupi por aqui?).
# TODO
- [ ] Guidelines
  
   Resolução de gravação, tamanho da fonte, cores, ...
- [ ] Passo a passo
  
    Para gravação e edição.
# Tópicos

**Por favor edite esse comentário para adicionar mais tópicos.**
- [ ] Instalação do Anaconda
- [ ] Explorando Spyder. @leportella?
- [ ] Pandas
- [ ] Álgebra Linear
- [ ] Matplotlib
- [ ] ggplot2 com Python
- [ ] Bokeh
- [ ] SymPy
- [ ] Regressão Linear/Espacial (scipy, statsmodels ou pysal)

**Comment by melissawm** [comment]
Posso fazer um de álgebra linear! Só fico em dúvida sobre profundidade do
assunto e tempo. Tenho umas vídeo aulas sobre quadrados mínimos que posso
adaptar pra Python... Pode ser?
Em 06/02/2016 3:21 PM, "Raniere Silva" notifications@github.com escreveu:

**Comment by xmnlab** [comment]
@melissawm, acho que ia ser muito legal :)

**Comment by ocefpaf** [comment]
:+1:  para a ideia e +:100:  para os videos de álgebra linear (com sympy?)!

@melissawm acho que o ideal é fazer vídeos bem pequenos ~2-5 minutos para que sejam **assistidos**  mesmo.  Mesmo que faça uma sequência de videos pequenos.

Sou péssimo pra falar em vídeo senão fazia um também :grin:

**Comment by melissawm** [comment]
Não uso sympy... Se alguém quiser fazer algo assim, eu não tenho
experiência. Posso falar de álgebra linear numérica. 2 a 5 min é bem curto
mas tenho algumas idéias desde que possa ser algo ligeiramente mais
avançado :)
Em 07/02/2016 5:12 PM, "Filipe" notifications@github.com escreveu:

**Comment by alexdesiqueira** [comment]
Caros, meus dois contos:
- creio que nos vídeos seria interessante trabalhar com assuntos mais elementares, de forma a introduzir os assuntos. @melissawm, acho que uma introdução às matrizes e operações no numpy, por exemplo, seria bem bacana.
- creio que 2-5 min seja bem curto. Acho que até uns 15 min dava pra engolir; o ideal pra desenvolver uma ideia, na minha cabeça, seria algo em torno de 1 hora, editado em 4 - 5 módulos.
  O que vocês acham?

**Comment by xmnlab** [comment]
Acho legal a ideia de ser um video de 1 hora dividido em módulos. talvez em 3 partes de 20 mins cada.

Acho que devemos nos focar em temas introdutórios.  Mas seria muito legal também uns avançados :)

**Comment by ocefpaf** [comment]
Videos de 2-5 min é complicado mesmo. ~15 min provavelmente é uma meta mais realista.  Quebrar em partes também é uma boa opção para reduzir o tamanho e prender a atenção da audiência.

Mas acho que quanto menor maiores são as chances de sucesso.  Essa geração Google não para mais de 2-3 minutes em video-aula a não ser que o apresentador seja muito bom de "show."

Tinha um cara que fazia videos de 2 minutos ensinando Python no Youtube que era um sucesso.  Não me lembro o nome do canal...

**Comment by alexdesiqueira** [comment]
@xmnlab @melissawm temas mais avançados são muito bacanas, desde que o espectador tenha a base pra vê-los. Por isso os mais básicos, depois os mais avançados, como uma construção. Mas são só minhas humildes opiniões :)

@ocefpaf pensamos na ideia dos módulos por isso mesmo, velho. Creio que 10 - 15 min sejam bacanas porque acho complicado falar de algumas coisas em 2 min e ainda deixar inteligível... mas essa é a base da ideia. Vídeos ligeiramente curtos, mas sem descuidar da didática.

**Comment by xmnlab** [comment]
Em relação aos videos avançados, é legal porque temos público desse nível também.
Assim a gente agrada a todos :D

**Comment by melissawm** [comment]
Vou tentar mandar uma proposta pra vcs mais tarde e aí vcs podem opinar pra
me ajudar ok? Tô com umas ideias já :)
Em 07/02/2016 5:54 PM, "Ivan" notifications@github.com escreveu:

**Comment by xmnlab** [comment]
adicionando o @gileno na conversa :)

**Comment by xmnlab** [comment]
Alguém poderia assumir ou indicar alguém para assumir essa issue e organizar essa atividade? :)

**Comment by rgaiacs** [comment]
@alexandrejaguar Alguma chance de conseguir fazer um pequeno screenshare nesse mês?

**Comment by rgaiacs** [comment]
Abandonado.
